name: Notification-app CI Build and Test

on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    name: Build and Deploy Notification-App
    runs-on: ubuntu-latest

    steps:
      # Checkout source code
      - name: Checkout Code
        uses: actions/checkout@v4

      # Setup JDK 17
      - name: Setup JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: "corretto"
          java-version: 17

      # Run Unit Tests
      - name: Unit Tests
        run: mvn -B test --file pom.xml

      # Build application with Maven
      - name: Build the application
        run: |
          mvn clean
          mvn -B package --file pom.xml

      # Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v4

      # Login to Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      # Build & Push Docker Image
      - name: Build & Push Docker Image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/notification-app-ci-build-and-test:latest
